"""Make email nullable

Revision ID: 42e94ba164bb
Revises: c9d2a7f3e5b1
Create Date: 2026-01-02 17:12:55.043401

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42e94ba164bb"
down_revision = "c9d2a7f3e5b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_column("rendered_body_cache")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("rendered_body_cache")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rendered_body_cache", sa.TEXT(), nullable=True))

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rendered_body_cache", sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
