"""Add is_master to Tag model

Revision ID: 5ff44ef94951
Revises: 42e94ba164bb
Create Date: 2026-01-02 21:11:46.985318

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ff44ef94951"
down_revision = "42e94ba164bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_master", sa.Boolean(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("is_master")

    # ### end Alembic commands ###
