"""Add comments_enabled field to Post model

Revision ID: 7bfb6721a44a
Revises: e06c5c873070
Create Date: 2025-11-07 08:29:38.501852

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bfb6721a44a"
down_revision = "e06c5c873070"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comments_enabled", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("comments_enabled")

    # ### end Alembic commands ###
