"""Add is_draft field
       to Post model

Revision ID: b8588fe609f8
Revises: 7bfb6721a44a
Create Date: 2025-11-12 19:48:46.333368

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8588fe609f8"
down_revision = "7bfb6721a44a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_draft", sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_post_is_draft"), ["is_draft"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_is_draft"))
        batch_op.drop_column("is_draft")

    # ### end Alembic commands ###
