"""Add rendered_body_cache fields for performance optimization

Revision ID: c9d2a7f3e5b1
Revises: b8588fe609f8
Create Date: 2025-11-14 11:45:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9d2a7f3e5b1"
down_revision = "b8588fe609f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rendered_body_cache", sa.Text(), nullable=True))

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rendered_body_cache", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_column("rendered_body_cache")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("rendered_body_cache")

    # ### end Alembic commands ###
